### ISSUE TITLE
Changes in contributing.md file

### ISSUE THREAD

**Issue by ADITYADAS1999** [ADITYADAS1999/Awesome_Resume_Builder#10]
Remove the highlighted section from [contributing.md](https://github.com/ADITYADAS1999/Awesome_Resume_Builder/blob/main/Contribution.md#:~:text=On%20the%20top,you%20have%20created.) file and add the below text

- If you want to change a file just click on the pencil icon on top right of the file name, to edit the file and add necessary changes.

- After editing the necessary changes on the files, add a commit message and click on the green button saying "Commit Changes". Make sure you have selected the branch you have created.

**Comment by FortyJags** [comment]
Hi, I would be happy to make this change.

**Comment by ADITYADAS1999** [comment]
Closes at #11
